-- use our accountadmin role
USE ROLE accountadmin;

-- DATABASE 
CREATE OR REPLACE DATABASE CORTEX_ANALYST_DEMO;

-- SCHEMA
CREATE OR REPLACE STAGE STAGE SEMANTIC_MODELS;

-- WAREHOUSE
CREATE OR REPLACE WAREHOUSE CORTEX_ANALYST_DEMO_WH AUTO_SUSPEND = 60;
